# Generated by Django 3.2.7 on 2021-09-22 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_ticket_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='time_create',
            new_name='time_created',
        ),
    ]
